### ISSUE TITLE
[FR] Support discussions

### ISSUE THREAD

**Issue by DhruvaSambrani** [meiji163/gh-notify#46]
Can we support discussions in the notifications?

**Comment by LangLangBart** [comment]
- Generating a preview is not supported and `gh` has no interest in adding this functionality natively
  - Ref: https://github.com/cli/cli/issues/5659#issuecomment-1137585847
- But we could at least provide a way to open the discussion URL with a hotkey in the browser 
  - it's a bit cumbersome, since the information we get from the REST API endpoint for the `discussion` notification doesn't give us much usable info
    - Ref: [Github Docs: notifications](https://docs.github.com/en/rest/activity/notifications) 
  - I started an attempt in PR #29
    - has since been put on hold as I felt it took too much time to do the individual queries. Around ~5s more.
