### ISSUE TITLE
`ctrl-b` doesn't work on issues

### ISSUE THREAD

**Issue by rEnr3n** [meiji163/gh-notify#55]
1. Run `gh notify`
2. Press `ctrl-b` on an issue

Nothing happens. It works as expected for releases.

**Comment by LangLangBart** [comment]
- proabaly because of the `open` command
  - in 7bdc2c4 the idea was to check if the issue/pr has a `last comment url` and use that url instead of the default `gh` behavior
- can you try both of these commands from the command line, I assume the 2nd won't work on non-macOS systems
```sh
# should open this ticket in the default web browser
gh issue view 55 --web --repo meiji163/gh-notify

# should do the same as above
open https://github.com/meiji163/gh-notify/issues/55
```

---

- does this python solution work for you
  - Ref: [StackOverflow: Shell script to open a URL](https://stackoverflow.com/questions/38147620/shell-script-to-open-a-url) (1/Jul/16)

```sh
python -m webbrowser "https://github.com/meiji163/gh-notify/issues/55"
```

- or this solution ?

```sh
url="https://github.com/meiji163/gh-notify/issues/55"

if uname | grep -q Darwin; then
    open "$url"
elif uname | grep -q Linux; then
    xdg-open "$url"
else
    start "$url"
fi
```

---

thanks for reporting

**Comment by rEnr3n** [comment]
I'm using linux. All of the commands you suggested work except for the `open` command. AFAIK, it's only available in macos. It doesn't exist on a linux system; `xdg-open` does.

**Comment by LangLangBart** [comment]
I pushed a fix, it would be helpful to leave a comment if it solved the problem for you

**Comment by rEnr3n** [comment]
Confirmed working.
