### ISSUE TITLE
mark as done via new api

### ISSUE THREAD

**Issue by andres-lowrie** [meiji163/gh-notify#78]
Hello

Looks like github added the following: https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28#mark-a-thread-as-done

Not sure if this would allow this tool to mark the notification as done now since before (I believe anyway) an api what was missing

**Comment by andres-lowrie** [comment]
referencing https://github.com/meiji163/gh-notify/issues/51

**Comment by andres-lowrie** [comment]
apologies ... (slaps forehead) my bad

**Comment by fredrikaverpil** [comment]
@andres-lowrie what was the problem here?
Why can't we implement a way to mark a notification as "done" and have the notifications sync with what you see at https://github.com/notifications ?

**Comment by fredrikaverpil** [comment]
@andres-lowrie what was the problem here?
Why can't we implement a way to mark a notification as "done" and have the notifications sync with what you see at https://github.com/notifications ?

Gitify managed to implement a "mark as done" ([here](https://github.com/gitify-app/gitify/pull/706) and [here](https://github.com/gitify-app/gitify/pull/1155)) which would be absolutely crucial (for me at least 😅 ) so to have any notifications mgmt dashboard sync up with GitHub's mobile app and/or online notifications UI.

**Comment by LangLangBart** [comment]
Ref: https://github.com/meiji163/gh-notify/issues/47#issuecomment-1974962747

**Comment by andres-lowrie** [comment]
> @andres-lowrie what was the problem here? Why can't we implement a way to mark a notification as "done" and have the notifications sync with what you see at https://github.com/notifications ?
> 
> Gitify managed to implement a "mark as done" ([here](https://github.com/gitify-app/gitify/pull/706) and [here](https://github.com/gitify-app/gitify/pull/1155)) which would be absolutely crucial (for me at least 😅 ) so to have any notifications mgmt dashboard sync up with GitHub's mobile app and/or online notifications UI.

Its been a minute but if I remember correctly I opened up this issue without looking at the other (the one posted by LangLangBart) one which already addressed the new api; I closed it so as to not make noise

**Comment by fredrikaverpil** [comment]
For what its worth, marking notifications as done works great in Gitify and it syncs both ways with github.com/notifications. So maybe it's possible to figure out some UX that makes sense here even if the API is not fully providing everything you originally wanted.
