### ISSUE TITLE
Allow filtering

### ISSUE THREAD

**Issue by NickLarsenNZ** [meiji163/gh-notify#97]
Sometimes I only want to see the notification where `org:MyOrg reason:mention`. For example, what would be displayed by: https://github.com/notifications?query=org%MyOrg+reason%3Amention

Would it be possible to add one or both of:
- An option to add a filter (not just text search)
- A config file in [`XDG_CONFIG_HOME`](https://specifications.freedesktop.org/basedir-spec/latest/index.html) where I can set static options

**Comment by LangLangBart** [comment]
The feature request is valid, but we can't easily implement it due to GitHub's API limitations. The `REST` and `GraphQL APIs` don't offer the notification filtering that's available in the `WebUI`.

- [REST API endpoints for notifications - GitHub Docs](https://docs.github.com/en/rest/activity/notifications)

We'll close this issue for now. If GitHub expands their API functionality in the future, we'll reconsider implementing this feature. 

The `REST API` for code search has the ability to use qualifiers (e.g., `user:defunkt extension:rb` _matches code from user defunkt that ends in .rb_) to narrow down searches. This shows that GitHub could potentially add similar functionality to the notifications API, but they have chosen not to so far.

- Ref: 
  - [REST API endpoints for search - GitHub Docs](https://docs.github.com/en/rest/search/search)
  - [Searching code (legacy) -  Qualifiers](https://docs.github.com/en/search-github/searching-on-github/searching-code)

---

Related issues also closed due to API limitations:
- #47
- #77
